DogsWebApp/Models/BreedType.cs
namespace DogsWebApp.Models
{
    public class BreedType
    {
        public int ID { get; set; }
        public int DogID { get; set; }
        public string Type { get; set; }

        public virtual Dog Dog { get; set; }
    }
}

DogsWebApp/Models/Dog.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DogsWebApp.Models
{
    public class Dog
    {
        public int ID { get; set; }

        [Required]
        public string Breed { get; set; }

        public virtual List<BreedType> Types { get; set; }
    }
}

DogsWebApp/Controllers/DogController.cs
using DogsWebApp.DAL;
using DogsWebApp.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace DogsWebApp.Controllers
{
    public class DogController : Controller
    {
        private DogsContext db = new DogsContext();

        // GET: Dog
        public ActionResult Index()
        {
            return View(db.Dogs.ToList());
        }

        // GET: Dog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // GET: Dog/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // POST: Dog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Dog dog, string submitDetails)
        {
            if (submitDetails.Equals("Back"))
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                // if the dog has sub types then add the dog object to the type since it won't get it from the model and then make sure the status is changed
                // so that it will be saved 
                if (dog.Types != null)
                {
                    dog.Types.ForEach(t =>
                    {
                        t.Dog = dog;
                        db.Entry(t).State = EntityState.Modified;
                    });

                    // removes any types from the list where the type is empty
                    var emptyTypes = dog.Types.Where(t => string.IsNullOrEmpty(t.Type));
                    if (emptyTypes != null)
                        db.BreedTypes.RemoveRange(emptyTypes);
                }

                db.Entry(dog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dog);
        }

        // GET: Dog/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // POST: Dog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dog dog = db.Dogs.Find(id);
            db.Dogs.Remove(dog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DogsWebApp/Views/Dog/Delete.cshtml
@model DogsWebApp.Models.Dog

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>

    <div class="form-group row col-md-10">
        @{int rowSpanCount = Model.Types.Count + 1; }

        <table class="table table-borderless">
            <tr>
                <td class="col-md-1">
                    @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-1" })
                </td>
                <td class="col-md-10">
                    @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                </td>
            </tr>
            @if (Model.Types.Count > 0)
            {
                <tr>
                    <td class="col-md-1" rowspan="@rowSpanCount">
                        @Html.LabelFor(model => model.Types, htmlAttributes: new { @class = "control-label col-md-1" })
                    </td>
                </tr>
                for (var count = 0; count < Model.Types.Count; count++)
                {
                    <tr>
                        <td class="col-md-10">
                            @Html.EditorFor(model => model.Types[count].Type, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    
    @Html.AntiForgeryToken()

    <div class="form-group row">
        <div class="col-md-offset-1 col-md-10">
            <button class="btn btn-danger" title="Delete" onclick="location.href='@Url.Action("Delete", "Dog",  new { id = Model.ID })'">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                Delete
            </button>
            <button class="btn btn-default" title="Go back to the list" onclick="location.href='@Url.Action("Index", "Dog")'">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                Back to List
            </button>
        </div>
    </div>

</div>

DogsWebApp/Views/Dog/Details.cshtml
@model DogsWebApp.Models.Dog

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <h2>Details</h2>

    <div class="form-group row col-md-10">
        @{int rowSpanCount = Model.Types.Count + 1; }

        <table class="table table-borderless">
            <tr>
                <td class="col-md-1"> 
                    @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-1" })
                </td>
                <td class="col-md-10">
                    @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                </td>
            </tr>
            @if (Model.Types.Count > 0)
            {
                <tr>
                    <td class="col-md-1" rowspan="@rowSpanCount">
                        @Html.LabelFor(model => model.Types, htmlAttributes: new { @class = "control-label col-md-1" })
                    </td>
                </tr>
                for (var count = 0; count < Model.Types.Count; count++)
                {
                    <tr>
                        <td class="col-md-10">
                            @Html.EditorFor(model => model.Types[count].Type, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <div class="form-group row">
        <div class="col-md-offset-1 col-md-10">
            <button class="btn btn-primary" title="Edit" onclick="location.href='@Url.Action("Edit", "Dog", new { id = Model.ID })'">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                Edit
            </button>
            <button class="btn btn-default" title="Back to List" onclick="location.href='@Url.Action("Index", "Dog")'">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                Back to List
            </button>
        </div>
    </div>
</div>

DogsWebApp/Views/Dog/Edit.cshtml
@model DogsWebApp.Models.Dog

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        int rowSpanCount = Model.Types.Count + 1;

        <div class="form-group row col-md-5">
            <table class="table table-borderless">
                <tr>
                    <td class="col-md-1">
                        @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-1" })
                    </td>
                    <td class="col-md-10">
                        @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
                    </td>
                </tr>
                @if (Model.Types.Count > 0)
                {
                    <tr>
                        <td class="col-md-1" rowspan="@rowSpanCount">
                            @Html.LabelFor(model => model.Types, htmlAttributes: new { @class = "control-label col-md-1" })
                        </td>
                    </tr>
                    for (var count = 0; count < Model.Types.Count; count++)
                    {
                        <tr>
                            @Html.HiddenFor(model => model.Types[count].ID)
                            @Html.HiddenFor(model => model.Types[count].DogID)

                            <td class="col-md-10">
                                @Html.EditorFor(model => model.Types[count].Type, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Types[count].Type, "", new { @class = "text-danger" })
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>

        <div class="form-group row">
            <div class="col-md-offset-1 col-md-10">
                <label for="saveBtn" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save</label>
                <input class="btn btn-primary" name="submitDetails" id="saveBtn" title="Save" type="submit" value="Save" style="display:none" />

                <label for="indexBtn" class="btn btn-default"><span class="glyphicon glyphicon-list"></span> Back to List</label>
                <input class="btn btn-primary" name="submitDetails" id="indexBtn" title="Back to list" type="submit" value="Back" style="display:none" />
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DogsWebApp/Views/Dog/Index.cshtml
@model IEnumerable<DogsWebApp.Models.Dog>

@{
    ViewBag.Title = "Dogs List";
}
<style>
    .row {
        padding-left: 0px;
    }

    .table {
        text-align: center
    }
</style>

<div class="container">
    <h2>Dogs list</h2>    

    <div class="row col-md-8">
        <table id="dogsDataTable" class="table table-bordered">
            <thead>
                <tr>
                    <th style="text-align: center;">Breed</th>
                    <th style="text-align: center;">Type</th>
                    <th style="text-align: center;">Controls</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    int rowSpan = item.Types.Count;

                    if (item.Types.Count > 0)
                    {
                        foreach (var type in item.Types)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Breed)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => type.Type)
                                </td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="...">
                                        <button class="btn btn-default" title="Edit" onclick="location.href='@Url.Action("Edit", "Dog",  new { id = item.ID })'">
                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                        </button>
                                        <button class="btn btn-info" title="More information" onclick="location.href='@Url.Action("Details", "Dog",  new { id = item.ID })'">
                                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                        </button>
                                        <button class="btn btn-danger" title="Delete" onclick="location.href='@Url.Action("Delete", "Dog",  new { id = item.ID })'">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Breed)
                            </td>
                            <td></td>
                            <td>
                                <div class="btn-group" role="group" aria-label="...">
                                    <button class="btn btn-default" title="Edit" onclick="location.href='@Url.Action("Edit", "Dog",  new { id = item.ID })'">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                    </button>
                                    <button class="btn btn-info" title="More information" onclick="location.href='@Url.Action("Details", "Dog",  new { id = item.ID })'">
                                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                    </button>
                                    <button class="btn btn-danger" title="Delete" onclick="location.href='@Url.Action("Delete", "Dog",  new { id = item.ID })'">
                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </button>
                                </div>

                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function ()
    {
        $('#dogsDataTable').DataTable({
            "columnDefs": [
                { "orderable": false, "targets": 1 }
            ],
            rowsGroup: [
                0,
                2
            ]
        });
    });
</script>

DogsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  Dogs Web Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    <script src="//cdn.rawgit.com/ashl1/datatables-rowsgroup/v1.0.0/dataTables.rowsGroup.js"></script>
</head>
<body>
    <style>
        .table-borderless > tbody > tr > td,
        .table-borderless > tbody > tr > th,
        .table-borderless > tfoot > tr > td,
        .table-borderless > tfoot > tr > th,
        .table-borderless > thead > tr > td,
        .table-borderless > thead > tr > th {
            border: none;
        }

        .table {
            margin-bottom: 0px;
        }
    </style>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dogs Web Application", "Index", "Dog", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Dogs Web Application - Ruvini</p>
        </footer>
    </div>

  
    @RenderSection("scripts", required: false)
</body>
</html>